services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
      #      - GF_SERVER_ROOT_URL=http://my.grafana.server/
      #      - GF_INSTALL_PLUGINS=grafana-clock-panel
      - GF_INSTALL_PLUGINS=grafana-piechart-panel

    ports:
      - '3000:3000'
    volumes:
      - './datasources:/etc/grafana/provisioning/datasources'
      - './backups/dashboards:/etc/grafana/provisioning/dashboards'
